
# PRELOAD action to do
# NEED TO IMPLEMENT - NOT NOW because I need to realize flight-controller
preload:
  command-to-exec-before:
  wait-at-boot: True
  seconds-to-wait: 0
  command-to-exec-after:

#-------------------------------------------------------------------------------------

#=====================================================
#      S E N S O R S   C O N F I G U R A T I O N
#=====================================================

motors-configuration:
  - single-motor-configuration:
      enable: true
      id: 1
      gpio_pin: 20
      min_value: 1100
      max_value: 1700
      driver-module: madis.core.motors
      driver-class: Motor

  - single-motor-configuration:
      enable: true
      id: 2
      gpio_pin: 16
      min_value: 1100
      max_value: 1700
      driver-module: madis.core.motors
      driver-class: Motor

  - single-motor-configuration:
      enable: false
      id: 3
      gpio_pin: 17
      min_value: 1100
      max_value: 1700
      driver-module: madis.core.motors
      driver-class: Motor

  - single-motor-configuration:
      enable: false
      id: 4
      gpio_pin: 18
      min_value: 1100
      max_value: 1700
      driver-module: madis.core.motors
      driver-class: Motor


#-------------------------------------------------------------------------------------

sensors-configuration:
  # Configuration for GPS
  gps: sensors/dummy_gps.yaml

  # Configuration for Accelerometer/Gyroscope
  stabilizer: sensors/dummy_accel_gyro.yaml

  # Configuration for Sonar (Obstacle Avoidance)
  obstacle-avoidance: sensors/dummy_sonar.yaml

  # Configuration for Enviromental sensor
  environment: sensors/dummy_temp_pressure.yaml

#-------------------------------------------------------------------------------------

network-configuration:
  - udp-client-configuration:
      sensor: gps
      name: gps_network_distributor
      distributor-module: mad.drone.core.subscribers.sensor_network_distributor
      distributor-class: SensorNetworkDistributor
      parameters: ["gps", "127.0.0.1", 10000]

  - udp-client-configuration:
      sensor: stabilizer
      name: stabilizer_network_distributor
      distributor-module: mad.drone.core.subscribers.sensor_network_distributor
      distributor-class: SensorNetworkDistributor
      parameters: ["stabilizer", "127.0.0.1", 10001]

  - udp-client-configuration:
      sensor: obstacle-avoidance
      name: obstacle_avoidance_network_distributor
      distributor-module: mad.drone.core.subscribers.sensor_network_distributor
      distributor-class: SensorNetworkDistributor
      parameters: ["obstacle-avoidance", "127.0.0.1", 10002]

  - udp-client-configuration:
      sensor: environment
      name: environment_network_distributor
      distributor-module: mad.drone.core.subscribers.sensor_network_distributor
      distributor-class: SensorNetworkDistributor
      parameters: ["environment", "127.0.0.1", 10003]


